// created by ftxi on 2025/9/18
// implementing tessaract's hypercuboid algorithm

#ifndef HYPERCUBOID_H
#define HYPERCUBOID_H

#include <map>
#include <set>
#include <vector>
#include <variant>
#include <optional>
#include <string>
#include <memory>
#include <random>
#include <tuple>
#include <functional>
#include "geometry.h"
#include "state.h"
#include "vec4.h"
#include "generator.h"
#include "semimove.h"
#include "ordering.h"


/*
 `HC_info` is the class that implements the hypercuboid algorithm for
  generating all legal actions of a given state.

 Usage:

     auto [info, space] = HC_info::build_HC(s);
     for(moveseq mvs : info.search(std::move(space))) {
         // consume one legal action
     }

 `build_HC()` constructs both objects:
 - `HC_info`: the context of hypercuboid search
 - `search_space`: integer data that describes the range of candidate
 points to examine.
 A search space must only be used with the `HC_info` from the same call.

 To randomize the search order, construct a `random_HC_ordering` with the
 `universe` from `HC_info`, then pass it to `search()` or `iterative_search()`.

 Terminology and representation:

 - An axis represents one playable timeline or one possible new branching
   timeline. Axes [0, new_axis) are existing playable timelines; axes
   [new_axis, dimension) are possible new timelines.
 - An axis coordinate is an index into that axis's private `entry` table. An
   entry stores the semantic move together with algorithm-only data such as the
   resulting board and the matching departure index. `get_semimove(n, i)` is
   the public, read-only semantic projection of an entry.
 - A point chooses exactly one entry on every axis. It is a candidate action,
   not necessarily a legal one.
 - A hypercuboid (`HC`) is a Cartesian product of allowed coordinate sets. A
   `search_space` is a union of hypercuboids. `universe` contains every entry
   generated by `build_HC()`; the initial search space partitions that universe
   by the number of branching timelines used.
 - A slice describes a family of points sharing selected axis coordinates. If
   one candidate exposes a general problem, the corresponding slice can be
   removed instead of rejecting points one at a time.

 Candidate validation:

 - `take_point()` selects a point while pairing every arriving entry with its
   corresponding departing entry, so every superphysical move in the selected
   point is complete. It keeps the supplied hypercuboid synchronized by pruning
   arrivals after their departures become unavailable.
 - Passing `jump_order_consistent()` means the paired superphysical moves can
   be performed in axis order and the point can be reconstructed as a move
   sequence.
 - Futher passing `test_present()` means that move sequence advances the Present.
 - Further passing `find_checks()` means the moving player's royal pieces
   are safe after the move sequence. Therefore it is submitted as a legal action.
 - `find_problem()` applies those three checks in order. It returns
   `std::nullopt` when all guarantees hold; otherwise it returns a slice sharing
   the discovered problem so the search can remove all affected candidates.
 - `to_action()` reconstructs the complete `full_move` sequence from a valid
   point. It reads private entries, so no information is lost through the
   semantic `semimove` projection.

 Search policies:

 All *search() methods work roughly by performing this loop:
 1. take a point from the search space
 2. find a problem slice for that point
 3. if no problem, yield the point's action sequence
 4. otherwise, remove the problem slice from the search space and repeat

 Differences are in how problem slices are removed and propagated through the search space:
 - `iterative_search()` removes a discovered problem only from the currently
   examined hypercuboid.
 - `stable_search()` propagates each problem slice through every remaining
   hypercuboid, limiting fragmentation with careful removal.
 - `search()` is the default adaptive policy. It propagates a problem through
   nearby intersecting hypercuboids while those intersections remain dense.
 - `mixed_search()` uses stable propagation until the first result for states
   spanning at least ten timelines, then continues iteratively.
*/

class HC_info
{
    struct physical_entry
    {
        full_move m;
        std::shared_ptr<board> b;
    };
    struct arriving_entry
    {
        full_move m;
        std::shared_ptr<board> b;
        index_t idx;
    };
    struct departing_entry
    {
        vec4 from;
        std::shared_ptr<board> b;
    };
    struct null_entry {};
    using entry = std::variant<physical_entry, arriving_entry, departing_entry, null_entry>;

    static semimove to_semimove(const entry &e);
    static std::shared_ptr<board> extract_board(const entry &e);
    static std::pair<int, int> extract_tl(const entry &e);
    std::vector<std::vector<entry>> axis_coords;

public:
    // local variables
    const state s;
    const std::map<int, index_t> line_to_axis; // map from timeline index to axis index
    HC_info(state s, std::map<int, index_t> lm, std::vector<std::vector<entry>> crds, HC uni, index_t ax, index_t dim, const std::vector<int> pl)
        : axis_coords(std::move(crds)), s(std::move(s)), line_to_axis(std::move(lm)), universe(std::move(uni)), new_axis(ax), dimension(dim), mandatory_lines(pl) {}
    semimove get_semimove(index_t n, index_t i) const;

    HC universe;
    const index_t new_axis, dimension; // axes 0, 1, ..., new_axis-1 are playable lines
    // whereas new_axis, new_axis+1, ..., dimension-1 are the possible branching lines
    // identity: dimension = universe axis count = axis_coords.size()
    const std::vector<int> mandatory_lines;
    
    /*
     take_point(): takes a point in hc while making sure arrives matches 
     departures.
     If it finds an arrive with its departure no longer in hc, then this
     arrives get deleted immediately (that's why parameter hc is a
     non-const reference)
     */
    std::optional<point> take_point(HC &hc) const;
    template<HC_ordering Order>
    std::optional<point> take_point(HC &hc, const Order &order) const;
    
    /*
     find_problem(p, hc): find any problem about p and returns the problem 
     slice in hc or std::nullopt if the point is okay
     There are three layers: if the point passes
     + jump_order_consistent: then the departure semimoves and arrival semimoves are good pairs, thus the point is avialible for to_action to get a moveseq;
     + test_present: then the point actually pushes the Present foward, but may still contain checks
     + find_checks: then the point is all good for a valid action
     */
    std::optional<slice> find_problem(const point &p, const HC &hc) const;
    std::optional<slice> jump_order_consistent(const point &p, const HC &hc) const;
    std::optional<slice> test_present(const point &p, const HC &hc) const;
    std::optional<slice> find_checks(const point &p, const HC &hc) const;
    moveseq to_action(const point &p) const;
    static std::tuple<HC_info, search_space> build_HC(const state &s);
    generator<moveseq> search(search_space ss) const;
    template<HC_ordering Order>
    generator<moveseq> search(search_space ss, Order order) const;
    generator<moveseq> iterative_search(search_space ss) const;
    template<HC_ordering Order>
    generator<moveseq> iterative_search(search_space ss, Order order) const;
    generator<moveseq> stable_search(search_space ss) const;
    generator<moveseq> mixed_search(search_space ss) const;
    // /* uncomment when debugging */
    //std::vector<moveseq> search1(search_space ss) const;
};

#include "hypercuboid.inl"

#endif /* HYPERCUBOID_H */
